// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently, but
// are changed infrequently
//

#pragma once

// Prevent headers from creating min/max macros so that no conflicts
// will be generated by using functions with these names.
#define NOMINMAX  1

#include "targetver.hpp"

#include <stdio.h>
#include <tchar.h>
#include <string>

#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers
// Windows Header Files:
#include <windows.h>

// Additional common libraries required
#include <direct.h>

// TODO: reference additional headers your program requires here

// Axis System Base Library
#include "AxisString.hpp"

// macros definitions
#include "macros.hpp"

// Undefine min/max macros
#ifdef min
#undef min
#endif

#ifdef max
#undef max
#endif